[package]
name = "tonescript"
description = "Tonescript。Rust だけで書いた音楽制作環境。"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "tone"
path = "src/main.rs"

[dependencies]
tonescript-dsp = { path = "../dsp" }
tonescript-song = { path = "../song" }
tonescript-render = { path = "../render" }
tonescript-project = { path = "../project" }
tonescript-midi = { path = "../midi" }
